definitions:
  go-echo-v2_internal_handlers_healthcheck.OKResponse:
    properties:
      message:
        example: Health Check OK !!
        type: string
    type: object
  healthcheck.InternalServerErrorResponse:
    properties:
      message:
        example: 'Failed to health check: error message'
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Go言語（Golang）のフレームワーク「Echo」によるAPI開発サンプルのバージョン２
  title: go-echo-v2 API
  version: "1.0"
paths:
  /api/v1/:
    get:
      description: テキスト「Hello World !!」を出力する。
      responses:
        "200":
          description: OK
      tags:
      - index
  /api/v1/healthcheck:
    get:
      description: APIとDBの接続確認をするためのヘルスチェックAPI
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-echo-v2_internal_handlers_healthcheck.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/healthcheck.InternalServerErrorResponse'
      security:
      - Bearer: []
      tags:
      - healthcheck
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
