services:
  api:
    container_name: echo-api-v2
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
      - pg-db
  pg-db:
    container_name: echo-db-v2
    build:
      context: .
      dockerfile: ./docker/local/db/Dockerfile
    environment:
      - POSTGRES_DB=pg-db
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pg-password
      - POSTGRES_INITDB_ARGS=--locale=ja_JP.utf8
      - TZ=Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - ./docker/local/db/init:/docker-entrypoint-initdb.d
      - pg-db-data:/var/lib/postgresql/data
volumes:
  pg-db-data:
    driver: local